import { useDrizzle, tables, eq, inArray } from '#server/utils/drizzle';
import { z } from 'zod';
import { count, desc } from 'drizzle-orm';
import { recordAuditEventFromRequest } from '#server/utils/audit';
import { getValidatedQuery, requireAccountUser } from '#server/utils/security';

defineRouteMeta({
  openAPI: {
    tags: ['Account'],
    summary: 'List API keys',
    description:
      'Retrieves a paginated list of all personal API keys generated by the authenticated user.',
    parameters: [
      {
        in: 'query',
        name: 'page',
        schema: { type: 'integer', default: 1 },
        description: 'Page number for pagination',
      },
      {
        in: 'query',
        name: 'limit',
        schema: { type: 'integer', default: 50, maximum: 100 },
        description: 'Number of items per page',
      },
    ],
    responses: {
      200: {
        description: 'API keys successfully retrieved',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      identifier: { type: 'string' },
                      description: { type: 'string', nullable: true },
                      allowed_ips: { type: 'array', items: { type: 'string' } },
                      last_used_at: { type: 'string', format: 'date-time', nullable: true },
                      created_at: { type: 'string', format: 'date-time' },
                    },
                  },
                },
                pagination: {
                  type: 'object',
                  properties: {
                    page: { type: 'integer' },
                    perPage: { type: 'integer' },
                    total: { type: 'integer' },
                    totalPages: { type: 'integer' },
                  },
                },
              },
            },
          },
        },
      },
      401: { description: 'Authentication required' },
      500: { description: 'Internal server error' },
    },
  },
});

export default defineEventHandler(async (event) => {
  const accountContext = await requireAccountUser(event);
  const user = accountContext.user;

  const db = useDrizzle();
  const { page, limit } = await getValidatedQuery(
    event,
    z.object({
      page: z.coerce.number().min(1).catch(1).default(1),
      limit: z.coerce.number().min(1).max(100).catch(50).default(50),
    }),
  );
  const offset = (page - 1) * limit;

  const totalResult = await db
    .select({ count: count() })
    .from(tables.apiKeys)
    .where(eq(tables.apiKeys.userId, user.id));

  const total = totalResult[0]?.count ?? 0;

  const keys = await db
    .select({
      id: tables.apiKeys.id,
      name: tables.apiKeys.name,
      expiresAt: tables.apiKeys.expiresAt,
      createdAt: tables.apiKeys.createdAt,
    })
    .from(tables.apiKeys)
    .where(eq(tables.apiKeys.userId, user.id))
    .orderBy(desc(tables.apiKeys.createdAt))
    .limit(limit)
    .offset(offset);

  if (!keys.length) {
    await recordAuditEventFromRequest(event, {
      actor: user.id,
      actorType: 'user',
      action: 'account.api_keys.listed',
      targetType: 'user',
      targetId: user.id,
      metadata: { page, limit, total, returned: 0 },
    });

    return {
      data: [],
      pagination: {
        page,
        perPage: limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  const keyIds = keys.map((key) => key.id);

  const keyPermissions = await db
    .select({
      apiKeyId: tables.apiKeyMetadata.apiKeyId,
      memo: tables.apiKeyMetadata.memo,
      allowedIps: tables.apiKeyMetadata.allowedIps,
      lastUsedAt: tables.apiKeyMetadata.lastUsedAt,
    })
    .from(tables.apiKeyMetadata)
    .where(inArray(tables.apiKeyMetadata.apiKeyId, keyIds));

  const permsByKeyId = new Map(keyPermissions.map((p) => [p.apiKeyId, p]));

  const data = keys.map((key) => {
    const perms = permsByKeyId.get(key.id);

    let allowedIps: string[] = [];
    if (perms?.allowedIps) {
      if (typeof perms.allowedIps === 'string') {
        try {
          const parsed = JSON.parse(perms.allowedIps);
          allowedIps = Array.isArray(parsed) ? parsed : [];
        } catch {
          allowedIps = perms.allowedIps
            .split(',')
            .map((ip: string) => ip.trim())
            .filter(Boolean);
        }
      } else if (Array.isArray(perms.allowedIps)) {
        allowedIps = perms.allowedIps;
      }
    }

    return {
      identifier: key.id,
      description: perms?.memo || key.name || null,
      allowed_ips: allowedIps,
      last_used_at: perms?.lastUsedAt || null,
      created_at: key.createdAt,
    };
  });

  await recordAuditEventFromRequest(event, {
    actor: user.id,
    actorType: 'user',
    action: 'account.api_keys.listed',
    targetType: 'user',
    targetId: user.id,
    metadata: { page, limit, total, returned: keys.length },
  });

  return {
    data,
    pagination: {
      page,
      perPage: limit,
      total,
      totalPages: Math.ceil(total / limit),
    },
  };
});
